# Import your ruby version
FROM ruby:3.1.3-alpine


# Install dependencies
RUN apk update && apk add \
  curl \
  vim \
  jq \
  git


# Gemfile, Gemfile.lock, .ruby-version to docker
ADD Gemfile Gemfile.lock .ruby-version ./
# install bundler
ENV BUNDLER_VERSION='2.4'
RUN gem install bundler --no-document -v '2.4'

# Load our Gemfile
COPY Gemfile* ./

WORKDIR /work

# install app dependencies
ENV BUNDLE_PATH /gems
RUN bundle install

# Assign a work directory
COPY . /work
RUN cp .env.dist .ENV





