# FROM ruby:3.1.3-alpine3.17

# RUN apk update && apk add --no-cache \
#     curl \
#     vim \
#     jq \
#     git \
#     build-base \
#     mysql-client \
#     mysql-server \
#     apk add --no-cache nodejs yarn

# WORKDIR /crispy-octo
# COPY Gemfile Gemfile.lock ./
# RUN gem install bundler
# RUN bundle install
# COPY . .

# EXPOSE 3000
# CMD ["rails", "server", "-b", "0.0.0.0"]



# Utilisez une image de base contenant Ruby et les outils nécessaires
FROM ruby:3.1.3

# Définit le répertoire de travail dans le conteneur
WORKDIR /app

# Copie du Gemfile et du Gemfile.lock dans le conteneur
COPY Gemfile Gemfile.lock ./

# Installation des gems
RUN bundle install

# Copie de tout le code source dans le conteneur
COPY . .

# Expose le port utilisé par votre application
EXPOSE 3000

# Commande par défaut pour démarrer votre application
CMD ["rails", "server", "-b", "0.0.0.0"]