# Utilisez une image de base contenant Ruby et les outils nécessaires
FROM ruby:3.1.3

RUN apt-get update

# Définit le répertoire de travail dans le conteneur
WORKDIR /app

# Copie du Gemfile et du Gemfile.lock dans le conteneur
COPY Gemfile Gemfile.lock ./

# Installation des gems
RUN bundle install

# Copie de tout le code source dans le conteneur
COPY . .

# Expose le port utilisé par votre application
EXPOSE 3000

# Commande par défaut pour démarrer votre application
CMD ["rails", "server", "-b", "0.0.0.0"]
