apiVersion: v1
kind: ConfigMap
metadata:
  name: crispy-octo-configmap
data:
  nginx-config: |
    user nginx;
    worker_process 1;
    events {
      worker_connection 10240;
    }
    http {
      server {
        listen 80
        server_name _;
        location / {
          root /crispy-octo/nginx/html;
          index index.html index.html;
        }
      }
    }
