apiVersion: v1
data:
  DATABASE_URL: bXlzcWwyOi8vcHJvZHVjdGlvbjpFdmRIYk5tMEdwZjEuQDUxLjE1OS4yNi4yMjM6ODY4Mi9yZGI/cG9vbD01
  REDIS_URL: cmVkaXM6Ly9oZXRpY3RlYW1zZXB0cmVkaXM6SGV0aWN0ZWFtNyFAMjEyLjQ3LjI1My45Njo2Mzc5Lw==
  EMAIL_PASSWORD: ZnIxMjI2
  EMAIL_USERNAME: amV0QGdtYWlsLmNvbQ==
kind: Secret
type: Opaque
metadata:
  name: app-secrets