apiVersion: apps/v1
kind: Deployment
metadata:
  name: crispy-octo-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crispy-octo-worker
  template:
    metadata:
      labels:
        app: crispy-octo-worker
    spec:
      containers:
        - name: crispy-octo-worker
          image: crispy-octo-worker:latest
          imagePullPolicy: Always
          command: ["bundle", "exec", "rake", "environment", "resque:work", "QUEUE=*", "RAILS_ENV=development"]
          env:
            - name: MYSQL_USER
              value: production
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: REDIS_URL
            - name: EMAIL_PORT
              value: "587"
            - name: EMAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: EMAIL_USERNAME
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: EMAIL_PASSWORD
            - name: EMAIL_FROM
              value: test@hotmail.fr
